### ISSUE TITLE
IndexError when running outputClean.py

### ISSUE THREAD

**Issue by Tmacphee13** [brianbeliveau/OligoMiner#28]
I'm seeing an Index out of range issue when running cleanOutput.py. The fastq and input sam files were generated with blockParse and bowtie2 against bowtie2 generated GRCh38 index respectively.

``
(probeMining) root@83eb7974bb0f:/app/OligoMiner# python outputClean.py -u -f work/sam/sense_26_32_u.sam
Traceback (most recent call last):
  File "outputClean.py", line 486, in <module>
    main()
  File "outputClean.py", line 480, in main
    reportVal, debugVal, metaVal, outNameVal, startTime)
  File "outputClean.py", line 70, in cleanOutput
    if x[0] is not '@' else ' ' for x in file_read]
IndexError: list index out of range
``

Running OligoMiner in container built with environment.yml file provided in repo:

```
(probeMining) root@83eb7974bb0f:/app/OligoMiner# conda list
# packages in environment at /root/miniconda3/envs/probeMining:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
biopython                 1.70                np112py27_1    bioconda
blas                      1.1                    openblas    conda-forge
bowtie2                   2.3.5.1          py27he513fc3_0    bioconda
ca-certificates           2024.8.30            hbcca054_0    conda-forge
certifi                   2019.11.28       py27h8c360ce_1    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
jellyfish                 2.2.10               h6bb024c_1    bioconda
jemalloc                  4.5.0                         0    bioconda
jpeg                      9e                   h0b41bf4_3    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_1    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc                    14.1.0               h77fa898_1    conda-forge
libgcc-ng                 14.1.0               h69a702a_1    conda-forge
libgfortran-ng            7.5.0               h14aa051_20    conda-forge
libgfortran4              7.5.0               h14aa051_20    conda-forge
libgfortran5              14.1.0               hc5f4f2c_1    conda-forge
libgomp                   14.1.0               h77fa898_1    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libopenblas               0.3.21               h043d6bf_0
libpng                    1.6.43               h2797004_0    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libstdcxx                 14.1.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.1.0               h4852527_1    conda-forge
libtiff                   4.3.0                h0fcbabc_4    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
mmtf-python               1.0.2                    py27_0    bioconda
msgpack-python            1.0.0            py27h9e3301b_1    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
numpy                     1.12.1          py27_blas_openblash1522bff_1001    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openblas                  0.3.3             h9ac9557_1001    conda-forge
openssl                   1.1.1w               hd590300_0    conda-forge
perl                      5.32.1          7_hd590300_perl5    conda-forge
pillow                    6.2.1            py27hd70f55b_1    conda-forge
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
python                    2.7.15          h5a48372_1011_cpython    conda-forge
python_abi                2.7                    1_cp27mu    conda-forge
readline                  8.2                  h8228510_1    conda-forge
reportlab                 3.5.42           py27heca39a3_0    conda-forge
scikit-learn              0.20.4          py27_blas_openblashebff5e3_0    conda-forge
scipy                     1.2.1            py27h09a28d5_1    conda-forge
setuptools                44.0.0                   py27_0    conda-forge
sqlite                    3.46.0               h6d4b2fc_0    conda-forge
tbb                       2020.2               h4bd325d_4    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```

**Comment by brianbeliveau** [comment]
Hi,

Can you please paste a snippet of your .fastq file (first ~10 lines is fine) and verify you are getting alignments reported in your .sam file (ie, your reads are not failing to align to reference)

**Comment by Tmacphee13** [comment]
Hi Brian,

I think that might be the culprit! I have a significant number of reads not aligning, seems like I may have some things to work out upstream. Thank you for your quick response.
